services:
  - type: web
    name: CoasterDPI
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: '10000'
      - key: DATABASE_URL
        value: 'postgresql://user:RYw873tYkMT8RMgZ3gNuaWiBzxxfdQY6@dpg-cuhd3ud2ng1s7384s7u0-a.frankfurt-postgres.render.com/coasterdpi05_db'
    plan: free
