services:
  - type: web
    name: DPIHaLong
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: '10000' 
      - key: DATABASE_URL
        value: 'postgresql://user:xfvSmfHvJAhxuVMtsnkiBnHAjLkiHtlf@dpg-d3vgtmf5r7bs73875qbg-a.singapore-postgres.render.com/dpihalong_db_01'
    plan: free
