services:
  - type: web
    name: CoasterDPI
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: '10000'
      - key: DATABASE_URL
        value: 'postgresql://user:QAIsHkOIEuuWyN3j0Y5Qrvpy8Kk5Hbe8@dpg-cvidl2d6ubrc73da3910-a.frankfurt-postgres.render.com/coasterdpi09_db'
    plan: free
